service: word-herd
env: flex
runtime: java
liveness_check:
  path: "/actuator/health"
  check_interval_sec: 60
env_variables:
  SPRING_PROFILES_ACTIVE: "appengine"
manual_scaling:
  instances: 1
resources:
  cpu: 2
  memory_gb: 4
